#ifndef __DEFAULT_CMDS_H
#define __DEFAULT_CMDS_H

#define CONFIG_CMD_BDI
#define CONFIG_CMD_BEDBUG
#define CONFIG_CMD_I2C
#define CONFIG_CMD_EXT2
#define CONFIG_CMD_LOADB
#define CONFIG_CMD_LOADS
#define CONFIG_CMD_NET
#define CONFIG_CMD_RARP
#define CONFIG_CMD_RUN
#define CONFIG_CMD_SETEXPR

#endif
